spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/memor2
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: tlgus0210


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  jwt:
    secretKey: ed4667fac1ca35c325e7298c05cd71e8f7d0ae5b46b48c3956cdc9b587ca5d0e
    expiration: 172800000    # 48??
    refreshExpiration: 604800000 # 7?